openapi: 3.0.0
info:
  title: Dish Booking API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /signup:
    post:
      summary: Register user
  /login:
    post:
      summary: Login user
  /dishes:
    get:
      summary: List dishes
  /orders:
    post:
      summary: Create order
  /forgot-password:
    post:
      summary: Request password reset
  /reset-password/{token}:
    post:
      summary: Reset password
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
